# Generated by Django 4.2.3 on 2023-08-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_portfolio_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Member',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': "Bizning jamoa a'zolari"},
        ),
    ]
